<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Module;
use Illuminate\Database\Seeder;

/**
 * ModulesSeeder - Seeds the core ERP modules
 */
class ModulesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $modules = [
            [
                'module_key' => 'pos',
                'slug' => 'pos',
                'name' => 'Point of Sale',
                'name_ar' => 'نقطة البيع',
                'description' => 'POS terminal for retail sales, quick checkout, and payment processing',
                'description_ar' => 'نظام نقطة البيع للبيع بالتجزئة والدفع السريع',
                'icon' => 'shopping-cart',
                'is_core' => true,
                'is_active' => true,
                'sort_order' => 1,
                'category' => 'sales',
            ],
            [
                'module_key' => 'inventory',
                'slug' => 'inventory',
                'name' => 'Inventory Management',
                'name_ar' => 'إدارة المخزون',
                'description' => 'Products, categories, stock levels, transfers, and warehouse management',
                'description_ar' => 'إدارة المنتجات والفئات ومستويات المخزون والتحويلات',
                'icon' => 'cube',
                'is_core' => true,
                'is_active' => true,
                'sort_order' => 2,
                'category' => 'inventory',
                'has_inventory' => true,
                'has_serial_numbers' => true,
                'has_batch_numbers' => true,
            ],
            [
                'module_key' => 'sales',
                'slug' => 'sales',
                'name' => 'Sales Management',
                'name_ar' => 'إدارة المبيعات',
                'description' => 'Sales orders, invoices, quotations, returns, and customer transactions',
                'description_ar' => 'إدارة طلبات المبيعات والفواتير وعروض الأسعار والمرتجعات',
                'icon' => 'currency-dollar',
                'is_core' => true,
                'is_active' => true,
                'sort_order' => 3,
                'category' => 'sales',
            ],
            [
                'module_key' => 'purchases',
                'slug' => 'purchases',
                'name' => 'Purchases Management',
                'name_ar' => 'إدارة المشتريات',
                'description' => 'Purchase orders, requisitions, supplier quotations, and goods receiving',
                'description_ar' => 'إدارة أوامر الشراء وطلبات الشراء وعروض الموردين',
                'icon' => 'truck',
                'is_core' => true,
                'is_active' => true,
                'sort_order' => 4,
                'category' => 'procurement',
            ],
            [
                'module_key' => 'crm',
                'slug' => 'crm',
                'name' => 'Customer Relations',
                'name_ar' => 'علاقات العملاء',
                'description' => 'Customer management, loyalty programs, and customer analytics',
                'description_ar' => 'إدارة العملاء وبرامج الولاء وتحليلات العملاء',
                'icon' => 'user-group',
                'is_core' => true,
                'is_active' => true,
                'sort_order' => 5,
                'category' => 'sales',
            ],
            [
                'module_key' => 'accounting',
                'slug' => 'accounting',
                'name' => 'Accounting & Finance',
                'name_ar' => 'المحاسبة والمالية',
                'description' => 'Chart of accounts, journal entries, banking, expenses, and income',
                'description_ar' => 'دليل الحسابات والقيود اليومية والبنوك والمصروفات والإيرادات',
                'icon' => 'calculator',
                'is_core' => true,
                'is_active' => true,
                'sort_order' => 6,
                'category' => 'finance',
            ],
            [
                'module_key' => 'hrm',
                'slug' => 'hrm',
                'name' => 'Human Resources',
                'name_ar' => 'الموارد البشرية',
                'description' => 'Employee management, attendance, leaves, and payroll',
                'description_ar' => 'إدارة الموظفين والحضور والإجازات والرواتب',
                'icon' => 'users',
                'is_core' => false,
                'is_active' => true,
                'sort_order' => 7,
                'category' => 'hr',
            ],
            [
                'module_key' => 'rental',
                'slug' => 'rental',
                'name' => 'Rental Management',
                'name_ar' => 'إدارة الإيجارات',
                'description' => 'Properties, units, tenants, contracts, and rental invoices',
                'description_ar' => 'إدارة العقارات والوحدات والمستأجرين والعقود',
                'icon' => 'home',
                'is_core' => false,
                'is_active' => true,
                'sort_order' => 8,
                'category' => 'rental',
                'is_rental' => true,
            ],
            [
                'module_key' => 'projects',
                'slug' => 'projects',
                'name' => 'Project Management',
                'name_ar' => 'إدارة المشاريع',
                'description' => 'Projects, tasks, milestones, time tracking, and project expenses',
                'description_ar' => 'إدارة المشاريع والمهام والمراحل وتتبع الوقت',
                'icon' => 'folder',
                'is_core' => false,
                'is_active' => true,
                'sort_order' => 9,
                'category' => 'projects',
            ],
            [
                'module_key' => 'manufacturing',
                'slug' => 'manufacturing',
                'name' => 'Manufacturing',
                'name_ar' => 'التصنيع',
                'description' => 'Bill of materials, production orders, work centers, and manufacturing transactions',
                'description_ar' => 'قائمة المواد وأوامر الإنتاج ومراكز العمل',
                'icon' => 'cog',
                'is_core' => false,
                'is_active' => true,
                'sort_order' => 10,
                'category' => 'manufacturing',
            ],
            [
                'module_key' => 'vehicles',
                'slug' => 'vehicles',
                'name' => 'Vehicle & Spare Parts',
                'name_ar' => 'المركبات وقطع الغيار',
                'description' => 'Vehicle management, warranties, spare parts compatibility',
                'description_ar' => 'إدارة المركبات والضمانات وتوافق قطع الغيار',
                'icon' => 'truck',
                'is_core' => false,
                'is_active' => true,
                'sort_order' => 11,
                'category' => 'automotive',
            ],
            [
                'module_key' => 'helpdesk',
                'slug' => 'helpdesk',
                'name' => 'Help Desk',
                'name_ar' => 'مركز المساعدة',
                'description' => 'Support tickets, SLA policies, and customer support management',
                'description_ar' => 'تذاكر الدعم وسياسات مستوى الخدمة وإدارة دعم العملاء',
                'icon' => 'ticket',
                'is_core' => false,
                'is_active' => true,
                'sort_order' => 12,
                'category' => 'support',
                'is_service' => true,
            ],
            [
                'module_key' => 'documents',
                'slug' => 'documents',
                'name' => 'Document Management',
                'name_ar' => 'إدارة المستندات',
                'description' => 'File storage, versioning, sharing, and document workflows',
                'description_ar' => 'تخزين الملفات والإصدارات والمشاركة وسير عمل المستندات',
                'icon' => 'document',
                'is_core' => false,
                'is_active' => true,
                'sort_order' => 13,
                'category' => 'documents',
            ],
            [
                'module_key' => 'reports',
                'slug' => 'reports',
                'name' => 'Reports & Analytics',
                'name_ar' => 'التقارير والتحليلات',
                'description' => 'Business intelligence, dashboards, scheduled reports, and data export',
                'description_ar' => 'ذكاء الأعمال ولوحات المعلومات والتقارير المجدولة',
                'icon' => 'chart-bar',
                'is_core' => true,
                'is_active' => true,
                'sort_order' => 14,
                'category' => 'analytics',
                'supports_reporting' => true,
            ],
            [
                'module_key' => 'settings',
                'slug' => 'settings',
                'name' => 'System Settings',
                'name_ar' => 'إعدادات النظام',
                'description' => 'System configuration, users, roles, and branch settings',
                'description_ar' => 'إعدادات النظام والمستخدمين والأدوار وإعدادات الفرع',
                'icon' => 'cog-6-tooth',
                'is_core' => true,
                'is_active' => true,
                'sort_order' => 15,
                'category' => 'system',
            ],
        ];

        foreach ($modules as $moduleData) {
            Module::updateOrCreate(
                ['module_key' => $moduleData['module_key']],
                $moduleData
            );
        }
    }
}
