<?php

declare(strict_types=1);

namespace App\Services;

use App\Enums\SaleStatus;
use App\Models\Product;
use App\Models\PurchaseRequisition;
use App\Models\PurchaseRequisitionItem;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;

/**
 * StockReorderService - Automated stock reorder management
 *
 * NEW FEATURE: Automated stock monitoring and reorder suggestions
 *
 * FEATURES:
 * - Identify products that need reordering
 * - Calculate optimal reorder quantities
 * - Generate purchase requisitions automatically
 * - Consider lead times and sales velocity
 * - Support for min/max inventory levels
 *
 * SECURITY (V40-SQL-13): SQL Expression Safety - REVIEWED
 * ========================================================
 * This service uses whereRaw() with variable interpolation.
 * All interpolated values are SAFE because they come from validated sources:
 *
 * 1. $stockSubquery: Generated by StockService::getBranchStockCalculationExpression()
 *    - Validates column names via regex pattern
 *    - Validates branch ID as positive integer
 *
 * 2. Column names ('products.id', 'products.branch_id') are hardcoded
 *
 * 3. Comparison columns (reorder_point, stock_alert_threshold) are hardcoded schema names
 *
 * @security-reviewed V40 - SQL expressions validated via StockService regex validation
 */
class StockReorderService
{
    /**
     * Get all products that need reordering.
     *
     * V9-CRITICAL-01 FIX: Use stock_movements as source of truth instead of stock_quantity
     * V10-CRITICAL-01 FIX: Use branch-scoped stock calculation to prevent cross-branch leakage
     *
     * SECURITY NOTE: The $stockSubquery is generated by StockService::getBranchStockCalculationExpression()
     * which validates all column names against SQL injection using strict regex patterns.
     * No user input flows into the SQL expression.
     *
     * @security-reviewed V43 - $stockSubquery is validated by StockService regex patterns
     */
    public function getProductsNeedingReorder(?int $branchId = null): Collection
    {
        // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
        // SECURITY: StockService validates column names with regex before interpolation
        $stockSubquery = \App\Services\StockService::getBranchStockCalculationExpression('products.id', 'products.branch_id');

        // @phpstan-ignore-next-line - $stockSubquery is regex-validated by StockService
        $query = Product::query()
            ->whereNotNull('reorder_point')
            ->whereRaw("({$stockSubquery}) <= reorder_point")
            ->where('status', 'active')
            ->where('type', '!=', 'service')
            ->with(['branch', 'module', 'unit']);

        if ($branchId) {
            $query->where('branch_id', $branchId);
        }

        return $query->get();
    }

    /**
     * Get products with low stock (above reorder point but below alert threshold).
     *
     * V9-CRITICAL-01 FIX: Use stock_movements as source of truth instead of stock_quantity
     * V10-CRITICAL-01 FIX: Use branch-scoped stock calculation to prevent cross-branch leakage
     *
     * SECURITY NOTE: The $stockSubquery is generated by StockService::getBranchStockCalculationExpression()
     * which validates all column names against SQL injection using strict regex patterns.
     * No user input flows into the SQL expression.
     *
     * @security-reviewed V43 - $stockSubquery is validated by StockService regex patterns
     */
    public function getLowStockProducts(?int $branchId = null): Collection
    {
        // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
        // SECURITY: StockService validates column names with regex before interpolation
        $stockSubquery = \App\Services\StockService::getBranchStockCalculationExpression('products.id', 'products.branch_id');

        // @phpstan-ignore-next-line - $stockSubquery is regex-validated by StockService
        $query = Product::query()
            ->whereNotNull('stock_alert_threshold')
            ->whereRaw("({$stockSubquery}) <= stock_alert_threshold")
            ->whereRaw("({$stockSubquery}) > COALESCE(reorder_point, 0)")
            ->where('status', 'active')
            ->where('type', '!=', 'service')
            ->with(['branch', 'module', 'unit']);

        if ($branchId) {
            $query->where('branch_id', $branchId);
        }

        return $query->get();
    }

    /**
     * Calculate optimal reorder quantity for a product.
     * V10-CRITICAL-01 FIX: Use branch-specific sales velocity
     */
    public function calculateReorderQuantity(Product $product): float
    {
        // Use predefined reorder quantity if available
        if ($product->reorder_qty && $product->reorder_qty > 0) {
            return decimal_float($product->reorder_qty, 4);
        }

        // V10-CRITICAL-01 FIX: Calculate sales velocity for the product's branch
        $salesVelocity = $this->calculateSalesVelocity($product->id, 30, $product->branch_id);

        if ($salesVelocity > 0) {
            // Order enough for 30 days plus buffer
            $optimalQty = $salesVelocity * 30 * 1.2; // 20% buffer

            // Respect minimum order quantity
            if ($product->minimum_order_quantity && $optimalQty < $product->minimum_order_quantity) {
                return decimal_float($product->minimum_order_quantity, 4);
            }

            // Respect maximum order quantity
            if ($product->maximum_order_quantity && $optimalQty > $product->maximum_order_quantity) {
                return decimal_float($product->maximum_order_quantity, 4);
            }

            // V30-MED-08 FIX: Use bcround() instead of bcdiv truncation
            return decimal_float(bcround((string) $optimalQty, 4), 4);
        }

        // FIX: Use bcmul for financial precision instead of float multiplication
        return $product->reorder_point ? decimal_float(bcmul((string) decimal_float($product->reorder_point, 4), '2', 4), 4) : 50;
    }

    /**
     * Calculate average daily sales velocity.
     * V10-CRITICAL-01 FIX: Add optional branch filter for branch-specific calculations
     * V35-HIGH-02 FIX: Use sale_date instead of created_at for accurate period filtering
     * V35-MED-06 FIX: Exclude soft-deleted sales and non-revenue statuses
     * V46-HIGH-02 FIX: Exclude soft-deleted sale_items
     */
    private function calculateSalesVelocity(int $productId, int $days = 30, ?int $branchId = null): float
    {
        $query = DB::table('sale_items')
            ->join('sales', 'sale_items.sale_id', '=', 'sales.id')
            ->where('sale_items.product_id', $productId)
            ->whereNull('sales.deleted_at')
            ->whereNull('sale_items.deleted_at')
            ->whereNotIn('sales.status', SaleStatus::nonRevenueStatuses())
            ->where('sales.sale_date', '>=', now()->subDays($days));

        // V10-CRITICAL-01 FIX: Filter by branch to get branch-specific sales velocity
        if ($branchId !== null) {
            $query->where('sales.branch_id', $branchId);
        }

        $totalSold = $query->sum('sale_items.quantity');

        // FIX: Use bcdiv for financial precision instead of float division
        return $totalSold ? decimal_float(bcdiv((string) decimal_float($totalSold), (string) $days, 4), 4) : 0;
    }

    /**
     * Generate reorder suggestions with details.
     *
     * V9-CRITICAL-01 FIX: Use stock_movements as source of truth for stock values
     * V10-CRITICAL-01 FIX: Use branch-scoped stock and sales velocity calculations
     */
    public function generateReorderSuggestions(?int $branchId = null): array
    {
        $products = $this->getProductsNeedingReorder($branchId);

        return $products->map(function (Product $product) {
            $reorderQty = $this->calculateReorderQuantity($product);
            // V10-CRITICAL-01 FIX: Use branch-specific sales velocity
            $salesVelocity = $this->calculateSalesVelocity($product->id, 30, $product->branch_id);
            // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation via helper method
            $currentStock = \App\Services\StockService::getStock($product->id, $product->branch_id);
            $daysUntilStockout = $salesVelocity > 0
                ? ceil($currentStock / $salesVelocity)
                : null;

            return [
                'product_id' => $product->id,
                'product_name' => $product->name,
                'product_code' => $product->code,
                'sku' => $product->sku,
                'current_stock' => $currentStock,
                'reserved_stock' => $product->reserved_quantity,
                'available_stock' => $product->getAvailableQuantity(),
                'reorder_point' => $product->reorder_point,
                'suggested_quantity' => $reorderQty,
                'estimated_cost' => $reorderQty * ($product->standard_cost ?? 0),
                // V30-MED-08 FIX: Use bcround() instead of bcdiv truncation
                'sales_velocity' => decimal_float(bcround((string) $salesVelocity, 2)),
                'days_until_stockout' => $daysUntilStockout,
                'priority' => $this->calculatePriority($product, $daysUntilStockout),
                'branch_id' => $product->branch_id,
                'branch_name' => $product->branch->name ?? null,
            ];
        })->sortByDesc('priority')->values()->toArray();
    }

    /**
     * Calculate priority for reordering (1-5, 5 being highest).
     *
     * V9-CRITICAL-01 FIX: Use stock_movements as source of truth for stock levels
     * V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
     */
    private function calculatePriority(Product $product, ?int $daysUntilStockout): int
    {
        // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation via helper method
        $currentStock = \App\Services\StockService::getStock($product->id, $product->branch_id);

        // Out of stock = highest priority
        if ($currentStock <= 0) {
            return 5;
        }

        // Stock running out soon
        if ($daysUntilStockout !== null) {
            if ($daysUntilStockout <= 3) {
                return 5;
            } elseif ($daysUntilStockout <= 7) {
                return 4;
            } elseif ($daysUntilStockout <= 14) {
                return 3;
            }
        }

        // Below reorder point but not critical
        if ($product->reorder_point && $currentStock <= $product->reorder_point) {
            return 2;
        }

        return 1;
    }

    /**
     * Auto-generate purchase requisitions for products needing reorder.
     */
    public function autoGenerateRequisitions(?int $branchId = null, ?int $userId = null): array
    {
        $suggestions = $this->generateReorderSuggestions($branchId);

        if (empty($suggestions)) {
            return ['success' => true, 'message' => 'No products need reordering', 'requisitions' => []];
        }

        $requisitionsByBranch = collect($suggestions)
            ->filter(fn ($s) => $s['priority'] >= 3) // Only auto-generate for priority 3+
            ->groupBy('branch_id');

        $createdRequisitions = [];

        DB::transaction(function () use ($requisitionsByBranch, $userId, &$createdRequisitions) {
            foreach ($requisitionsByBranch as $branchId => $items) {
                $requisition = PurchaseRequisition::create([
                    'code' => 'REQ-AUTO-'.strtoupper(uniqid()),
                    'branch_id' => $branchId,
                    'status' => 'pending',
                    'priority' => 'high',
                    'requisition_date' => now(),
                    'required_by_date' => now()->addDays(7),
                    'notes' => 'Auto-generated requisition for low stock items',
                    'created_by' => $userId,
                ]);

                foreach ($items as $item) {
                    PurchaseRequisitionItem::create([
                        'requisition_id' => $requisition->id,
                        'product_id' => $item['product_id'],
                        'quantity' => $item['suggested_quantity'],
                        'estimated_price' => $item['estimated_cost'] / $item['suggested_quantity'],
                        'specifications' => "Current stock: {$item['current_stock']}, Reorder point: {$item['reorder_point']}",
                        'created_by' => $userId,
                    ]);
                }

                $createdRequisitions[] = [
                    'id' => $requisition->id,
                    'code' => $requisition->code,
                    'branch_id' => $branchId,
                    'items_count' => count($items),
                ];
            }
        });

        return [
            'success' => true,
            'message' => count($createdRequisitions).' requisitions created',
            'requisitions' => $createdRequisitions,
        ];
    }

    /**
     * Get reorder report statistics.
     */
    public function getReorderStatistics(?int $branchId = null): array
    {
        $needsReorder = $this->getProductsNeedingReorder($branchId)->count();
        $lowStock = $this->getLowStockProducts($branchId)->count();
        $outOfStock = Product::outOfStock()
            ->where('status', 'active')
            ->when($branchId, fn ($q) => $q->where('branch_id', $branchId))
            ->count();

        $suggestions = $this->generateReorderSuggestions($branchId);
        $totalEstimatedCost = collect($suggestions)->sum('estimated_cost');

        return [
            'products_needing_reorder' => $needsReorder,
            'products_low_stock' => $lowStock,
            'products_out_of_stock' => $outOfStock,
            // V30-MED-08 FIX: Use bcround() instead of bcdiv truncation
            'total_estimated_cost' => decimal_float(bcround((string) $totalEstimatedCost, 2)),
            'high_priority_count' => collect($suggestions)->where('priority', '>=', 4)->count(),
        ];
    }
}
