<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\Customer;
use App\Models\Product;
use App\Models\RentalContract;
use App\Models\Supplier;
use Illuminate\Support\Facades\Log;

/**
 * WorkflowAutomationService - Automate business workflows and processes
 *
 * SECURITY (V37-SQL-14): SQL Expression Safety
 * =============================================
 * This service uses whereRaw(), selectRaw(), and orderByRaw() with variable interpolation.
 * All interpolated values are safe because:
 *
 * 1. $stockSubquery: Generated by StockService::getBranchStockCalculationExpression()
 *    which validates column names using regex patterns.
 *
 * 2. Column names passed to StockService: Always hardcoded strings
 *    ('products.id', 'products.branch_id').
 *
 * 3. Comparison columns (reorder_point, min_stock): Hardcoded column names.
 *
 * Static analysis tools may flag these patterns as SQL injection risks. This is a
 * false positive - the expressions are validated by StockService before interpolation.
 */
class WorkflowAutomationService
{
    /**
     * Check for low stock products and create alerts
     *
     * V9-CRITICAL-01 FIX: Use stock_movements as source of truth instead of stock_quantity
     * V10-CRITICAL-01 FIX: Use branch-scoped stock calculation to prevent cross-branch leakage
     */
    public function checkLowStockProducts(int $limit = 100): array
    {
        // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
        $stockSubquery = \App\Services\StockService::getBranchStockCalculationExpression('products.id', 'products.branch_id');

        $lowStockProducts = Product::query()
            ->whereRaw("({$stockSubquery}) <= COALESCE(reorder_point, min_stock, 0)")
            ->with(['category'])
            ->limit($limit)
            ->get();

        $alerts = [];
        foreach ($lowStockProducts as $product) {
            // V9-CRITICAL-01 FIX: Use stock_movements to get current stock
            // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
            $currentStock = \App\Services\StockService::getStock($product->id, $product->branch_id);
            $alerts[] = [
                'product_id' => $product->id,
                'product_name' => $product->name,
                'current_stock' => $currentStock,
                'reorder_point' => $product->reorder_point ?? $product->min_stock,
                'severity' => $this->calculateStockSeverity($product, $currentStock),
            ];
        }

        return $alerts;
    }

    /**
     * Calculate stock severity level
     *
     * V9-CRITICAL-01 FIX: Accept calculated stock as parameter instead of using stock_quantity
     * V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
     */
    protected function calculateStockSeverity(Product $product, ?float $currentStock = null): string
    {
        // V9-CRITICAL-01 FIX: Use provided stock or calculate from stock_movements
        // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
        $currentStock = $currentStock ?? \App\Services\StockService::getStock($product->id, $product->branch_id);
        $minStock = $product->min_stock ?? 0;
        $reorderPoint = $product->reorder_point ?? $minStock;

        if ($currentStock <= 0) {
            return 'critical';
        } elseif ($currentStock <= $minStock) {
            return 'high';
        } elseif ($currentStock <= $reorderPoint) {
            return 'medium';
        }

        return 'low';
    }

    /**
     * Check for expiring rental contracts
     */
    public function checkExpiringContracts(int $daysAhead = 30, int $limit = 100): array
    {
        $expiringContracts = RentalContract::query()
            ->where('status', 'active')
            ->whereDate('end_date', '<=', now()->addDays($daysAhead))
            ->whereDate('end_date', '>=', now())
            ->with(['unit.property', 'tenant'])
            ->limit($limit)
            ->get();

        $alerts = [];
        foreach ($expiringContracts as $contract) {
            $daysRemaining = now()->diffInDays($contract->end_date, false);

            $alerts[] = [
                'contract_id' => $contract->id,
                'tenant_name' => $contract->tenant?->name,
                'property_name' => $contract->unit?->property?->name,
                'unit_code' => $contract->unit?->code,
                'end_date' => $contract->end_date,
                'days_remaining' => (int) $daysRemaining,
                'renewal_notice_days' => $contract->renewal_notice_days ?? 30,
                'auto_renew' => $contract->auto_renew ?? false,
                'priority' => $daysRemaining <= 7 ? 'high' : 'normal',
            ];
        }

        return $alerts;
    }

    /**
     * Analyze customer payment patterns
     */
    public function analyzeCustomerPaymentPatterns(int $customerId): array
    {
        $customer = Customer::find($customerId);

        if (! $customer) {
            return [];
        }

        // This would typically query sales and payments
        // For now, return a structure showing what would be analyzed
        return [
            'customer_id' => $customer->id,
            'customer_name' => $customer->name,
            'payment_due_days' => $customer->payment_due_days ?? 30,
            'credit_limit' => $customer->credit_limit ?? 0,
            'avg_payment_delay' => 0, // Would be calculated from actual payments
            'total_outstanding' => 0, // Would be calculated from unpaid invoices
            'payment_reliability_score' => 100, // 0-100 scale
            'recommended_credit_limit' => $customer->credit_limit ?? 0,
        ];
    }

    /**
     * Evaluate supplier performance
     */
    public function evaluateSupplierPerformance(int $supplierId): array
    {
        $supplier = Supplier::find($supplierId);

        if (! $supplier) {
            return [];
        }

        return [
            'supplier_id' => $supplier->id,
            'supplier_name' => $supplier->name,
            'current_rating' => $supplier->supplier_rating ?? 'unrated',
            'lead_time_days' => $supplier->average_lead_time_days ?? 0,
            'on_time_delivery_rate' => 100, // Would be calculated from purchases
            'quality_rejection_rate' => 0, // Would be calculated from returns
            'price_competitiveness' => 'good', // Would be calculated from market data
            'recommended_rating' => 'A', // A, B, C, D based on metrics
        ];
    }

    /**
     * Generate reorder suggestions based on stock levels and sales velocity
     *
     * V9-CRITICAL-01 FIX: Use stock_movements as source of truth instead of stock_quantity
     * V10-CRITICAL-01 FIX: Use branch-scoped stock calculation to prevent cross-branch leakage
     */
    public function generateReorderSuggestions(int $limit = 50): array
    {
        // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
        $stockSubquery = \App\Services\StockService::getBranchStockCalculationExpression('products.id', 'products.branch_id');

        $products = Product::query()
            ->whereRaw("({$stockSubquery}) <= COALESCE(reorder_point, min_stock, 0)")
            ->with(['category'])
            ->selectRaw("*, ({$stockSubquery}) as calculated_stock")
            ->orderByRaw("(COALESCE(reorder_point, min_stock, 0) - ({$stockSubquery})) DESC")
            ->limit($limit)
            ->get();

        $suggestions = [];
        foreach ($products as $product) {
            // V9-CRITICAL-01 FIX: Use stock_movements to get current stock
            // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
            $currentStock = $product->calculated_stock ?? \App\Services\StockService::getStock($product->id, $product->branch_id);
            $reorderQuantity = $this->calculateReorderQuantity($product, $currentStock);

            $suggestions[] = [
                'product_id' => $product->id,
                'product_name' => $product->name,
                'sku' => $product->sku,
                'current_stock' => $currentStock,
                'min_stock' => $product->min_stock ?? 0,
                'max_stock' => $product->max_stock ?? 0,
                'reorder_point' => $product->reorder_point ?? 0,
                'suggested_order_quantity' => $reorderQuantity,
                'estimated_cost' => ($product->cost ?? 0) * $reorderQuantity,
                'lead_time_days' => $product->lead_time_days ?? 7,
                'urgency' => $this->calculateUrgency($product, $currentStock),
            ];
        }

        // Sort by urgency
        usort($suggestions, function ($a, $b) {
            $urgencyOrder = ['critical' => 0, 'high' => 1, 'medium' => 2, 'low' => 3];

            return ($urgencyOrder[$a['urgency']] ?? 99) <=> ($urgencyOrder[$b['urgency']] ?? 99);
        });

        return $suggestions;
    }

    /**
     * Calculate optimal reorder quantity
     *
     * V9-CRITICAL-01 FIX: Accept calculated stock as parameter instead of using stock_quantity
     * V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
     */
    protected function calculateReorderQuantity(Product $product, ?float $currentStock = null): float
    {
        // V9-CRITICAL-01 FIX: Use provided stock or calculate from stock_movements
        // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
        $currentStock = $currentStock ?? \App\Services\StockService::getStock($product->id, $product->branch_id);
        $maxStock = $product->max_stock ?? (($product->min_stock ?? 0) * 3);
        $minStock = $product->min_stock ?? 0;

        // Simple reorder formula: order to max stock level
        $reorderQty = max($maxStock - $currentStock, 0);

        return max($reorderQty, $minStock);
    }

    /**
     * Calculate urgency level for reordering
     *
     * V9-CRITICAL-01 FIX: Accept calculated stock as parameter instead of using stock_quantity
     * V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
     */
    protected function calculateUrgency(Product $product, ?float $currentStock = null): string
    {
        // V9-CRITICAL-01 FIX: Use provided stock or calculate from stock_movements
        // V10-CRITICAL-01 FIX: Use branch-scoped stock calculation
        $currentStock = $currentStock ?? \App\Services\StockService::getStock($product->id, $product->branch_id);
        $minStock = $product->min_stock ?? 0;

        // Calculate days of stock remaining based on average sales
        // For now, simplified urgency calculation
        if ($currentStock <= 0) {
            return 'critical';
        } elseif ($currentStock <= ($minStock * 0.5)) {
            return 'high';
        } elseif ($currentStock <= $minStock) {
            return 'medium';
        }

        return 'low';
    }

    /**
     * Log workflow event
     */
    protected function logWorkflowEvent(string $event, array $data): void
    {
        Log::channel('workflow')->info($event, $data);
    }
}
