<?php

declare(strict_types=1);

namespace App\Support;

use Illuminate\Contracts\Database\Query\Expression;
use Illuminate\Support\Facades\DB;

/**
 * ValidatedSqlExpression - A value object representing a validated SQL expression
 *
 * V40-SQL-SECURITY: Validated SQL Expression Wrapper
 * ===================================================
 * This class wraps SQL expressions that have been validated against SQL injection.
 * It provides type safety and makes the security intention explicit in the code.
 *
 * IMPORTANT: This class is a TYPE MARKER, not a validator.
 * It signifies that the expression was produced by a validating service.
 * The actual validation happens in StockService and DatabaseCompatibilityService
 * BEFORE the expression string is created.
 *
 * Factory Method Usage:
 *   - fromStockService(): For expressions from StockService (regex-validated)
 *   - fromDatabaseCompatibilityService(): For expressions from DatabaseCompatibilityService (regex-validated)
 *
 * Security Guarantee:
 *   The caller asserts that the SQL expression has been:
 *   1. Generated from a validating service (StockService or DatabaseCompatibilityService)
 *   2. NOT derived from user input
 *   3. Validated using appropriate regex patterns before creation
 *
 * @see \App\Services\StockService for stock calculation expressions (validates via regex)
 * @see \App\Services\DatabaseCompatibilityService for date/time expressions (validates via regex)
 */
final class ValidatedSqlExpression implements \Stringable
{
    /**
     * @param  string  $expression  The validated SQL expression
     */
    private function __construct(
        private readonly string $expression
    ) {}

    /**
     * Create a validated SQL expression from StockService.
     *
     * NOTE: StockService validates column names using regex pattern
     * /^[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)?$/ and throws
     * InvalidArgumentException on invalid input. The validation happens
     * BEFORE the expression string is generated.
     *
     * @param  string  $expression  Expression generated by StockService methods
     * @return static
     */
    public static function fromStockService(string $expression): self
    {
        return new self($expression);
    }

    /**
     * Create a validated SQL expression from DatabaseCompatibilityService.
     *
     * NOTE: DatabaseCompatibilityService validates column names using regex pattern
     * /^[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)?$/ and throws
     * InvalidArgumentException on invalid input. The validation happens
     * BEFORE the expression string is generated.
     *
     * @param  string  $expression  Expression generated by DatabaseCompatibilityService methods
     * @return static
     */
    public static function fromDatabaseCompatibilityService(string $expression): self
    {
        return new self($expression);
    }

    /**
     * Get the SQL expression string.
     */
    public function toString(): string
    {
        return $this->expression;
    }

    /**
     * Get as Laravel DB::raw expression.
     *
     * @security-reviewed V43 - This class wraps pre-validated SQL expressions.
     * The $expression property is guaranteed to be validated by the factory methods
     * (fromStockService, fromDatabaseCompatibilityService) which only accept
     * expressions from services that perform regex validation on all inputs.
     */
    public function toDbRaw(): Expression
    {
        // @phpstan-ignore-next-line - Expression is validated at creation time by factory methods
        return DB::raw($this->expression);
    }

    /**
     * Implements Stringable for convenient use in raw SQL contexts.
     */
    public function __toString(): string
    {
        return $this->expression;
    }
}
