<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class JournalEntry extends Model
{
    use SoftDeletes;

    protected $table = 'journal_entries';

    /**
     * Fillable fields aligned with migration:
     * 2026_01_04_000007_create_accounting_tables.php
     */
    protected $fillable = [
        'branch_id',
        'fiscal_period_id',
        'reference_number',
        'type',
        'entry_date',
        'description',
        'reference_type',
        'reference_id',
        'status',
        'total_debit',
        'total_credit',
        'currency',
        'exchange_rate',
        'reversed_entry_id',
        'reversed_by_entry_id',
        'created_by',
        'approved_by',
        'approved_at',
        'posted_at',
        // Source tracking fields used by AccountingService
        'source_module',
        'source_type',
        'source_id',
        'fiscal_year',
        'fiscal_period',
        'is_auto_generated',
    ];

    protected $casts = [
        'entry_date' => 'date',
        'total_debit' => 'decimal:4',
        'total_credit' => 'decimal:4',
        'exchange_rate' => 'decimal:8',
        'posted_at' => 'datetime',
        'approved_at' => 'datetime',
        'is_auto_generated' => 'boolean',
    ];

    protected $appends = ['reference'];

    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class);
    }

    public function fiscalPeriod(): BelongsTo
    {
        return $this->belongsTo(FiscalPeriod::class, 'fiscal_period_id');
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function approver(): BelongsTo
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    public function reversedEntry(): BelongsTo
    {
        return $this->belongsTo(JournalEntry::class, 'reversed_entry_id');
    }

    public function lines(): HasMany
    {
        return $this->hasMany(JournalEntryLine::class);
    }

    public function getReferenceAttribute(): string
    {
        return (string) ($this->reference_number ?? '');
    }

    public function getTotalDebitAttribute(): float
    {
        return (float) ($this->attributes['total_debit'] ?? $this->lines()->sum('debit'));
    }

    public function getTotalCreditAttribute(): float
    {
        return (float) ($this->attributes['total_credit'] ?? $this->lines()->sum('credit'));
    }

    public function isBalanced(): bool
    {
        return abs($this->total_debit - $this->total_credit) < 0.01;
    }

    public function scopeStatus(Builder $query, string $status): Builder
    {
        return $query->where('status', $status);
    }

    public function scopePosted(Builder $query): Builder
    {
        return $query->where('status', 'posted');
    }

    public function scopeDraft(Builder $query): Builder
    {
        return $query->where('status', 'draft');
    }

    // Backward compatibility accessors
    public function getIsAutoGeneratedAttribute(): bool
    {
        return $this->type === 'auto';
    }

    public function getIsReversibleAttribute(): bool
    {
        return $this->status === 'posted' && $this->reversed_entry_id === null;
    }
}
